export enum plantOrAnimal {
  PLANT = "PLANT",
  ANIMAL = "ANIMAL",
  BACKGROUND = "BACKGROUND",
  ANIMALMARKET = "ANIMALMARKET",
  PLANTMARKET = "PLANTMARKET",
  COW = "COW",
  CHICKEN = "CHICKEN",
  SHEEP = "SHEEP",
}
